version: 2
updates:
    - package-ecosystem: pip
      directory: /
      schedule:
        interval: weekly
        day: wednesday
        time: "11:00"
      allow:
        - dependency-type: all

    - package-ecosystem: github-actions
      directory: /
      schedule:
        interval: weekly
        day: wednesday
        time: "11:00"
      groups:
        actions:
          patterns:
            - "*"
